go_voyage_users:
    resource: "@GoVoyageBundle/Resources/config/routing/users.yml"
    prefix:   /users

go_voyage_homepage:
    path:     /
    defaults: { _controller: GoVoyageBundle:Default:index }
