go_voyage_users:
    resource: "@GoVoyageBundle/Resources/config/routing/users.yml"
    prefix:   /users

go_voyage_voyagepersonalise:
    resource: "@GoVoyageBundle/Resources/config/routing/voyagepersonalise.yml"
    prefix:   /voyagepersonalise

go_voyage_demande:
    resource: "@GoVoyageBundle/Resources/config/routing/demande.yml"
    prefix:   /demande

go_voyage_homepage:
    path:     /
    defaults: { _controller: GoVoyageBundle:Default:index }
